name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Generate timestamp tag
      id: tag_generator
      run: echo "::set-output name=tag::$(date +%Y%m%d%H%M%S)"

    - name: Build the Docker image
      # run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:${{ steps.tag_generator.outputs.tag }} .
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:$(git rev-parse --short HEAD) .  # Using Git commit hash

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:${{ steps.tag_generator.outputs.tag }}

    - name: Tag the Docker image as latest
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/backend:${{ steps.tag_generator.outputs.tag }} ${{ secrets.DOCKER_USERNAME }}/backend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest



    # docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:$(date +%Y.%m.%d) .  # Using version and date
    # OR
    # docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:$(git rev-parse --short HEAD) .  # Using Git commit hash
