name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Set Docker tag with shortened SHA
      id: docker_tag
      run: echo "::set-output name=tag::$(echo ${{ github.sha }} | cut -c1-8)"

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:${{ steps.docker_tag.outputs.tag }} .

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:${{ steps.docker_tag.outputs.tag }}

    - name: Tag the Docker image as latest
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/backend:${{ steps.docker_tag.outputs.tag }} ${{ secrets.DOCKER_USERNAME }}/backend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
