name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image to Docker Hub and GitHub Container Registry
      id: docker_build
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t ${{ secrets.DOCKER_USERNAME }}/backend:latest \
          -t ${{ secrets.DOCKER_USERNAME }}/backend:${IMAGE_TAG} \
          -t ghcr.io/${{ github.repository_owner }}/backend:latest \
          -t ghcr.io/${{ github.repository_owner }}/backend:${IMAGE_TAG} \
          --push .

    - name: Clean up Docker Buildx
      run: docker buildx rm
  
    - name: Logout from Docker Hub
      run: docker logout
  
    - name: Logout from GitHub Container Registry
      run: docker logout ghcr.io
